apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.ipfs.containerName }}
  namespace: {{ .Values.ipfs.namespace}}
  labels:
    app: {{ .Values.ipfs.containerName }}
spec:
  serviceName: {{ .Values.ipfs.containerName }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.ipfs.containerName }}
  template:
    metadata:
      labels:
        app: {{ .Values.ipfs.containerName }}
    spec:
      containers:
        - name: {{ .Values.ipfs.containerName }}
          image: "{{ .Values.ipfs.repository }}:{{ .Values.ipfs.tag }}"
          imagePullPolicy: {{ .Values.ipfs.pullPolicy }}
          ports:
          - containerPort: {{ .Values.ipfs.apiPort }}
            name: api
          - containerPort: {{ .Values.ipfs.gatewayPort }}
            name: gateway
          - containerPort: {{ .Values.ipfs.swarmPort }}
            name: swarm
  volumeClaimTemplates:
  - metadata:
      namespace: {{ .Values.ipfs.namespace}}
      name: {{ .Values.ipfs.containerName }}-volume-claim
      labels:
        app: {{ .Values.ipfs.containerName }}
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 5Gi
