[package]
name = "rust_node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.156"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]

[dependencies.reqwest]
version = "0.11.14"
features = ["json"]