version: '3'

env:
  PRIVATE_KEY: "0xac1e735be8536c6534bb4f17f06f6afc73b2b5ba84ac2cfb12f7461b20c0bbe3"

tasks:

  cargo-run:
    cmds:
      - cargo run
    env:
      ZKSYNC_API_URL: http://localhost:3050
      ZKSYNC_WS_URL: ws://localhost:3051
      IPFS_BASE_URL: http://localhost:5001
      CHECK_ID: false

  destroy-local:
    cmds:
      - helm uninstall node-ecosystem --wait || true
      - kubectl delete pvc --all || true
      - kubectl delete pv --all || true
      - colima stop || true

  start-local:
    cmds:
      - task build-images
      - task: start-k8s
      - task: deploy-ecosystem
    env:
      BUILD: '{{ .BUILD }}'

  deploy-ecosystem:
    cmds:
      - helm upgrade --install --wait --timeout 10m --set node.privateKey=$PRIVATE_KEY --set node.checkID=false node-ecosystem helm_chart/
      - helm test node-ecosystem

  start-k8s:
    cmds:
      - cp colima.yaml ~/.colima/_templates/colima.yaml
      - colima start --cpu 2 --memory 3 --runtime containerd --kubernetes
      - sleep 5 
    status:
      - colima status

  build-images:
    cmds:
      - colima stop || true
      - colima start --arch x86_64 --cpu 4 --memory 10 --runtime containerd
      - task compile-contract
      - nerdctl build -f images/toolbox.Dockerfile . -t toolbox:latest --namespace k8s.io
      - nerdctl build -f images/node.Dockerfile . -t node:latest --namespace k8s.io
      - colima stop
    env:
      BUILD: true
    status:
      - |
        if [ "$BUILD" != "true" ]
        then
          echo Skipping building Dockerfiles
          exit 0
        else
          echo Building Dockerfiles... 
          exit 1
        fi

  compile-contract:
    dir: 'contract'
    cmds:
      - yarn install
      - yarn hardhat compile
  
  integration-test:
    cmds:
      - ./integration_test.sh