version: '3'

tasks:

  pause:
    cmds:
      - docker pause $(docker ps -q --filter "name=kind-control-plane")
  
  unpause:
    cmds:
      - docker unpause $(docker ps -q --filter "name=kind-control-plane")

  destroy-local:
    cmds:
      - helm uninstall node-ecosystem --wait || true
      - kubectl delete pvc --all || true
      - kubectl delete pv --all || true
      - kind delete cluster || true
      - colima stop
      - colima delete

  start-local:
    cmds:
      - task: start-colima
      - task: start-kind
      - task docker-build 
      - task load-docker-images
      - task: deploy-ecosystem
    env:
      BUILD: '{{ .BUILD }}'

  deploy-ecosystem:
    internal: true
    cmds:
      - helm upgrade --install --wait --timeout 180s node-ecosystem helm_chart/
      - helm test node-ecosystem

  start-colima:
    internal: true
    cmds:
      - cp colima.yaml ~/.colima/_templates/colima.yaml
      - colima start --cpu 4 --memory 8
    status:
      - colima status

  start-kind:
    internal: true
    cmds:
      - kind create cluster --wait 45s
      - helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
      - helm repo update
      - helm upgrade --install --set args={--kubelet-insecure-tls} metrics-server metrics-server/metrics-server --namespace kube-system
    status:
      - kind get kubeconfig

  load-docker-images:
    cmds:
      - kind load docker-image toolbox:latest
      - kind load docker-image rust_node:latest

  docker-build:
    cmds:
      - docker build -f docker/rust_node_builder.Dockerfile . -t rust_node_builder:latest
      - docker build -f docker/toolbox.Dockerfile . -t toolbox:latest
      - |
        docker run --rm -it -v "$(pwd)":/rust_node rust_node_builder:latest \
          /bin/bash -c 'source "$HOME/.cargo/env" && cargo build --target x86_64-unknown-linux-musl --release'
      - docker build -f docker/rust_node.Dockerfile . -t rust_node:latest
    env:
      BUILD: true
    status:
      - |
        if [ "$BUILD" != "true" ]
        then
          echo Skipping building Dockerfiles
          exit 0
        else
          echo Building Dockerfiles... 
          exit 1
        fi
