apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.containerName }}-volume
  labels:
    type: local
    app: {{ .Values.postgres.containerName }}
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/postgresql"