apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.node.namespace}}
  name: {{ .Values.postgres.containerName }}
  labels:
    app: {{ .Values.postgres.containerName }}
spec:
  ports:
    - port: {{ .Values.postgres.containerPort }}
  selector:
    app: {{ .Values.postgres.containerName }}