apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.containerName }}
  namespace: {{ .Values.postgres.namespace}}
spec:
  serviceName: {{ .Values.postgres.containerName }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.containerName }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.containerName }}
    spec:
      containers:
      - name: {{ .Values.postgres.containerName }}
        image: "{{ .Values.postgres.repository }}:{{ .Values.postgres.tag }}"
        imagePullPolicy: {{ .Values.postgres.pullPolicy }}
        ports:
          - containerPort: {{ .Values.postgres.containerPort }}
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        volumeMounts:
          - mountPath: /var
            name: {{ .Values.postgres.containerName }}-volume-claim
  volumeClaimTemplates:
  - metadata:
      namespace: {{ .Values.postgres.namespace}}
      name: {{ .Values.postgres.containerName }}-volume-claim
      labels:
        app: {{ .Values.postgres.containerName }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
