apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.geth.containerName }}
  namespace: {{ .Values.geth.namespace}}
  labels:
    app: {{ .Values.geth.containerName }}
spec:
  ports:
  - port: {{ .Values.geth.httpPort }}
    protocol: TCP
    name: http
  - port: {{ .Values.geth.websocketPort }}
    protocol: TCP
    name: websocket
  selector:
    app: {{ .Values.geth.containerName }}