ipfs:
  repository: ipfs/kubo
  tag: master-2023-05-31-dfd2448
  pullPolicy: IfNotPresent

  containerName: ipfs
  apiPort: 5001
  gatewayPort: 8080
  swarmPort: 4001

  namespace: default

node:
  repository: rust_node
  tag: latest
  pullPolicy: Never

  containerName: node
  apiPort: 8000

  namespace: default

geth:
  repository: matterlabs/geth
  tag: latest
  # change this to IfNotPresent 
  pullPolicy: Never

  containerName: geth
  httpPort: 8545
  websocketPort: 8546

  namespace: default

postgres:
  repository: postgres
  tag: 12
  # change this to IfNotPresent 
  pullPolicy: Never

  containerName: postgres
  containerPort: 8545

  db: zksync
  user: serviceuser
  password: strongpasswordzk