ipfs:
  repository: ipfs/kubo
  tag: master-2023-05-31-dfd2448
  pullPolicy: IfNotPresent

  containerName: ipfs
  apiPort: 5001
  gatewayPort: 8080
  swarmPort: 4001

  namespace: default

node:
  repository: node
  tag: latest
  pullPolicy: Never

  initContainerRespository: toolbox
  initContainerTag: latest

  containerName: node
  apiPort: 8000

  namespace: default

  privateKey: ""
  checkID: ""

geth:
  repository: matterlabs/geth
  tag: latest
  pullPolicy: IfNotPresent

  containerName: geth
  httpPort: 8545
  websocketPort: 8546

  namespace: default

zksync:
  repository: matterlabs/local-node
  tag: latest2.0
  pullPolicy: IfNotPresent

  containerName: zksync
  httpPort: 3050
  websocketPort: 3051

  namespace: default

postgres:
  repository: postgres
  tag: 12
  pullPolicy: IfNotPresent 

  containerName: postgres
  containerPort: 5432

  namespace: default

  db: zksync