apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ipfs.containerName }}
  labels:
    app: {{ .Values.ipfs.containerName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.ipfs.containerName }}
  template:
    metadata:
      labels:
        app: {{ .Values.ipfs.containerName }}
    spec:
      containers:
        - name: {{ .Values.ipfs.containerName }}
          image: "{{ .Values.ipfs.repository }}:{{ .Values.ipfs.tag }}"
          imagePullPolicy: {{ .Values.ipfs.pullPolicy }}
          ports:
            - containerPort: 80
