apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{- with .Values.ipfsContainerName }}
  labels:
    app: {{- with .Values.ipfsContainerName }}
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: {{- with .Values.ipfsContainerName }}
#   template:
#     metadata:
#       labels:
#         app: {{- with .Values.ipfsContainerName }}
#     spec:
#       containers:
#         - name: {{- with .Values.ipfs.containerName }}
#           image: "{{ .Values.ipfs.repository }}:{{ .Values.ipfs.tag }}"
#           imagePullPolicy: {{ .Values.ipfs.pullPolicy }}
#           ports:
#             - containerPort: 80
