apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.node.containerName }}
  namespace: {{ .Values.node.namespace}}
  labels:
    run: {{ .Values.node.containerName }}
spec:
  ports:
  - port: {{ .Values.node.apiPort }}
    protocol: TCP
    name: api
  selector:
    app: {{ .Values.node.containerName }}