apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.node.containerName }}
  namespace: {{ .Values.node.namespace}}
  labels:
    app: {{ .Values.node.containerName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.node.containerName }}
  template:
    metadata:
      labels:
        app: {{ .Values.node.containerName }}
    spec:
      containers:
        - name: {{ .Values.node.containerName }}
          image: "{{ .Values.node.repository }}:{{ .Values.node.tag }}"
          imagePullPolicy: {{ .Values.node.pullPolicy }}
          command: ['sh', '-c', 'rust_node']
          ports:
          - containerPort: {{ .Values.node.apiPort }}
            name: api
          env:
          - name: ROCKET_ADDRESS
            value: "0.0.0.0"
          - name: IPFS_BASE_URL
            value: http://{{ .Values.ipfs.containerName}}.{{ .Values.ipfs.namespace}}:{{ .Values.ipfs.apiPort }}
          - name: ZKSYNC_BASE_HTTP_URL
            value: http://{{ .Values.zksync.containerName }}.{{ .Values.zksync.namespace}}:{{ .Values.zksync.httpPort}}
      initContainers:
        - name: init
          image: "{{ .Values.node.initContainerRespository }}:{{ .Values.node.initContainerTag }}"
          imagePullPolicy: {{ .Values.node.pullPolicy }}
          command:
            - sh
            - "-c"
            - |
              make_request() {
                  curl -s -X POST $ZKSYNC_BASE_HTTP_URL -H 'Content-Type: application/json' --data '{"jsonrpc": "2.0", "id": 1, "method": "zks_L1ChainId", "params": []}'
              }

              while make_request; [ $? -ne 0 ]; do
                  make_request
                  printf "\nWaiting for zksync to be available...\n"
                  sleep 5
              done
          env:
          - name: ZKSYNC_BASE_HTTP_URL
            value: http://{{ .Values.zksync.containerName }}.{{ .Values.zksync.namespace}}:{{ .Values.zksync.httpPort}}