apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.containerName }}-volume-claim
  labels:
    app: {{ .Values.postgres.containerName }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi