apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.containerName }}
  labels:
    app: {{ .Values.postgres.containerName }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.postgres.containerPort }}
  selector:
    app: {{ .Values.postgres.containerName }}